package com.gmpp.enums;
public enum TypeNotification { INTERVENTION_PLANIFIEE, INTERVENTION_EN_RETARD, STOCK_ALERTE_MIN, STOCK_ALERTE_MAX, PANNE_DECLAREE, PANNE_RESOLUE, VALIDATION_REQUISE, SYSTEME }
