export default {
  nav: { dashboard:'Dashboard', machines:'Machines', points:'Maintenance points', interventions:'Interventions', planning:'Planning', pannes:'Corrective maintenance', stock:'Spare parts', kpi:'KPI & Performance', techniciens:'Technicians', rapports:'Reports', audit:'Audit logs', notifications:'Notifications' },
  common: { add:'Add', edit:'Edit', delete:'Delete', save:'Save', cancel:'Cancel', confirm:'Confirm', search:'Search', filter:'Filter', export:'Export', close:'Close', loading:'Loading...', error:'Error', success:'Success', noData:'No data', all:'All', actions:'Actions', details:'Details', yes:'Yes', no:'No', refresh:'Refresh' },
  status: { PLANIFIEE:'Planned', EN_COURS:'In progress', TERMINEE:'Completed', ANNULEE:'Cancelled', EN_RETARD:'Overdue', EN_SERVICE:'In service', EN_MAINTENANCE:'Under maintenance', HORS_SERVICE:'Out of service', EN_REPARATION:'Under repair', DECLAREE:'Declared', RESOLUE:'Resolved', VALIDEE:'Validated', CRITIQUE:'Critical', HAUTE:'High', MOYENNE:'Medium', BASSE:'Low' },
  kpi: { mtbf:'MTBF', mttr:'MTTR', oee:'OEE', trs:'OEE (FR)', disponibilite:'Availability', performance:'Performance', qualite:'Quality', pannes:'Breakdowns', periode:'Period', mois:'Month', semaine:'Week', trimestre:'Quarter', annee:'Year' },
  machines: { title:'Machine management', add:'Add machine', nom:'Machine name', type:'Type', marque:'Brand', modele:'Model', serie:'Serial #', atelier:'Workshop', statut:'Status', compteur:'Operating hours' },
  stock: { title:'Spare parts inventory', reference:'Reference', designation:'Description', categorie:'Category', quantite:'Quantity', seuilMin:'Min threshold', prixUnit:'Unit price', alerte:'Alert', rupture:'Out of stock', entree:'Receipt', sortie:'Issue' },
  pannes: { title:'Corrective maintenance', declarer:'Report breakdown', resoudre:'Resolve', valider:'Validate', urgence:'Urgency', statut:'Status', machine:'Machine', technicien:'Technician', cause:'Root cause', actions:'Corrective actions' }
};
