export default {
  nav: { dashboard:'Tableau de bord', machines:'Machines', points:'Points maintenance', interventions:'Interventions', planning:'Planning', pannes:'Pannes correctives', stock:'Stock pièces', kpi:'KPI & Performance', techniciens:'Techniciens', rapports:'Rapports', audit:'Audit logs', notifications:'Notifications' },
  common: { add:'Ajouter', edit:'Modifier', delete:'Supprimer', save:'Enregistrer', cancel:'Annuler', confirm:'Confirmer', search:'Rechercher', filter:'Filtrer', export:'Exporter', close:'Fermer', loading:'Chargement...', error:'Erreur', success:'Succès', noData:'Aucune donnée', all:'Tous', actions:'Actions', details:'Détails', yes:'Oui', no:'Non', refresh:'Actualiser' },
  status: { PLANIFIEE:'Planifiée', EN_COURS:'En cours', TERMINEE:'Terminée', ANNULEE:'Annulée', EN_RETARD:'En retard', EN_SERVICE:'En service', EN_MAINTENANCE:'En maintenance', HORS_SERVICE:'Hors service', EN_REPARATION:'En réparation', DECLAREE:'Déclarée', RESOLUE:'Résolue', VALIDEE:'Validée', CRITIQUE:'Critique', HAUTE:'Haute', MOYENNE:'Moyenne', BASSE:'Basse' },
  kpi: { mtbf:'MTBF', mttr:'MTTR', oee:'OEE', trs:'TRS', disponibilite:'Disponibilité', performance:'Performance', qualite:'Qualité', pannes:'Nombre pannes', periode:'Période', mois:'Mois', semaine:'Semaine', trimestre:'Trimestre', annee:'Année' },
  machines: { title:'Gestion des machines', add:'Ajouter une machine', nom:'Nom machine', type:'Type', marque:'Marque', modele:'Modèle', serie:'N° Série', atelier:'Atelier', statut:'Statut', compteur:'Compteur horaire' },
  stock: { title:'Stock pièces de rechange', reference:'Référence', designation:'Désignation', categorie:'Catégorie', quantite:'Quantité', seuilMin:'Seuil min', prixUnit:'Prix unitaire', alerte:'En alerte', rupture:'Rupture', entree:'Entrée', sortie:'Sortie' },
  pannes: { title:'Maintenance corrective', declarer:'Déclarer une panne', resoudre:'Résoudre', valider:'Valider', urgence:'Urgence', statut:'Statut', machine:'Machine', technicien:'Technicien', cause:'Cause identifiée', actions:'Actions correctives' }
};
